# Generated by Django 4.1.7 on 2023-04-11 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_orderproduct_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='ordered',
        ),
    ]
