# Generated by Django 4.1.7 on 2023-04-12 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
