# Generated by Django 4.1.7 on 2023-04-14 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_delete_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='adress',
        ),
    ]
