# Generated by Django 4.1.7 on 2023-04-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_discount_product_price_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_discount',
            field=models.IntegerField(blank=True),
        ),
    ]
