# Generated by Django 4.1.7 on 2023-05-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_orderproduct_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
