# Generated by Django 4.1.7 on 2023-05-04 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_comment_marked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='marked',
        ),
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
