# Generated by Django 4.1.7 on 2023-05-09 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_product_photo'),
        ('store', '0021_alter_comment_rating'),
    ]

    operations = [
    ]
