# Generated by Django 4.1.7 on 2023-05-09 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_merge_20230509_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
